#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

USER=jjo
case "$1" in
  start)
    stat_busy "Starting rtorrent"
    #su - $USER -c 'screen -d -m -S rtorrent /home/jjo/bin/rtorrent-forever.sh' &> /dev/null
    su - $USER -c "tmux new-session -d -n rtorrent -s rtorrent bin/rtorrent-forever.sh" &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon rtorrent
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping rtorrent"
    killall -w -s 2 /usr/bin/rtorrent &> /dev/null
    #(fuser -k -15 /tmp/screens/S-$USER/*rtorrent;exit 0)
    #(fuser -k -15 /tmp/tmux-$(id -u $USER)/*)
    su - $USER -c "tmux kill-session -t rtorrent"
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon rtorrent
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"
esac
exit 0

